"""Added required tables

Revision ID: ba7a116a1efe
Revises: c4cfdc95421c
Create Date: 2022-09-16 16:31:46.264447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7a116a1efe'
down_revision = 'c4cfdc95421c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('projectManager', sa.String(), nullable=False),
    sa.Column('stack', sa.String(), nullable=False),
    sa.Column('productOwner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_id'), 'card', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_id'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
