"""Added required tables

Revision ID: c4cfdc95421c
Revises: bcdb3cbcd96f
Create Date: 2022-09-16 15:56:31.462050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cfdc95421c'
down_revision = 'bcdb3cbcd96f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
